Exception ValidateToken: :System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - The wait operation timed out.) ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at CCMSAutomationAPI.Models.JwtManager.GetSecretKey(String clientId) in C:\Users\Ayodeji.Olukowi\Downloads\CCMSAutomationAPI1\CCMSAutomationAPI\Models\JwtManager.cs:line 137
   at WebApi.Jwt.Filters.JwtAuthenticationAttribute.ValidateToken(String token, String clientId) in C:\Users\Ayodeji.Olukowi\Downloads\CCMSAutomationAPI1\CCMSAutomationAPI\Filters\JwtAuthenticationAttribute.cs:line 69
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:258,State:0,Class:20
StackTrace Date :14/03/2023 10:39:03

--------------------------------------------------------------------------

Exception AuthenticateAsync:    ddddd:help
StackTrace Date :14/03/2023 10:40:25

--------------------------------------------------------------------------

Exception GetSecretKey: :System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - The wait operation timed out.) ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at CCMSAutomationAPI.Controllers.TokenController.AgentAuthenticator(String clientId) in C:\Users\Ayodeji.Olukowi\Downloads\CCMSAutomationAPI1\CCMSAutomationAPI\Controllers\TokenController.cs:line 173
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:258,State:0,Class:20
StackTrace Date :14/03/2023 10:40:41

--------------------------------------------------------------------------

Exception GetToken: :Authenication Error/Unauthorised Access
StackTrace Date :14/03/2023 10:40:41

--------------------------------------------------------------------------

Exception AuthenticateAsync:    ddddd:help
StackTrace Date :14/03/2023 10:41:14

--------------------------------------------------------------------------

Exception GetSecretKey: :System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - The wait operation timed out.) ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at CCMSAutomationAPI.Controllers.TokenController.AgentAuthenticator(String clientId) in C:\Users\Ayodeji.Olukowi\Downloads\CCMSAutomationAPI1\CCMSAutomationAPI\Controllers\TokenController.cs:line 173
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:258,State:0,Class:20
StackTrace Date :14/03/2023 10:41:14

--------------------------------------------------------------------------

Exception GetToken: :Authenication Error/Unauthorised Access
StackTrace Date :14/03/2023 10:41:14

--------------------------------------------------------------------------

Exception AuthenticateAsync:    ddddd:help
StackTrace Date :14/03/2023 11:13:16

--------------------------------------------------------------------------

Exception GetToken: :Authenication Error/Unauthorised Access
StackTrace Date :14/03/2023 11:13:32

--------------------------------------------------------------------------

Exception AuthenticateAsync:    ddddd:help
StackTrace Date :14/03/2023 11:13:41

--------------------------------------------------------------------------

GetToken Notifications: :Access token generated successfully.
StackTrace Date :14/03/2023 11:13:41

--------------------------------------------------------------------------

SqlCommand: :1
StackTrace Date :14/03/2023 11:13:57

--------------------------------------------------------------------------

Insert Notifications: :Track Number: 39460 Successfully Inserted.
StackTrace Date :14/03/2023 11:14:04

--------------------------------------------------------------------------

SqlCommand: :1
StackTrace Date :14/03/2023 11:15:41

--------------------------------------------------------------------------

Insert Notifications: :Track Number: 39460 Successfully Inserted.
StackTrace Date :14/03/2023 11:29:41

--------------------------------------------------------------------------

Exception GetPrincipal: :Microsoft.IdentityModel.Tokens.SecurityTokenExpiredException: IDX10223: Lifetime validation failed. The token is expired. ValidTo: 'System.DateTime', Current time: 'System.DateTime'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
   at CCMSAutomationAPI.Models.JwtManager.GetPrincipal(String token, String clientId) in C:\Users\Ayodeji.Olukowi\Downloads\CCMSAutomationAPI1\CCMSAutomationAPI\Models\JwtManager.cs:line 83
StackTrace Date :14/03/2023 11:29:50

--------------------------------------------------------------------------

Exception AuthenticateAsync:    ddddd:help
StackTrace Date :14/03/2023 11:29:56

--------------------------------------------------------------------------

GetToken Notifications: :Access token generated successfully.
StackTrace Date :14/03/2023 11:29:56

--------------------------------------------------------------------------

SqlCommand: :1
StackTrace Date :14/03/2023 11:30:10

--------------------------------------------------------------------------

Exception InsertRequest StackMe:: :Conversion failed when converting the varchar value '3946R0' to data type int.
StackTrace Date :14/03/2023 11:30:10

--------------------------------------------------------------------------

Exception AuthenticateAsync:    ddddd:help
StackTrace Date :14/03/2023 11:45:07

--------------------------------------------------------------------------

GetToken Notifications: :Access token generated successfully.
StackTrace Date :14/03/2023 11:45:07

--------------------------------------------------------------------------

SqlCommand: :1
StackTrace Date :14/03/2023 11:45:24

--------------------------------------------------------------------------

Exception InsertRequest StackMe:: :Conversion failed when converting the varchar value '3946R0' to data type int.
StackTrace Date :14/03/2023 11:45:24

--------------------------------------------------------------------------

SqlCommand: :1
StackTrace Date :14/03/2023 11:45:32

--------------------------------------------------------------------------

Exception InsertRequest StackMe:: :Conversion failed when converting the varchar value '3946R0' to data type int.
StackTrace Date :14/03/2023 11:45:32

--------------------------------------------------------------------------

SqlCommand: :1
StackTrace Date :14/03/2023 11:48:52

--------------------------------------------------------------------------

Exception InsertRequest StackMe:: :Procedure or function Proc_ccms_comp_detail_DCM has too many arguments specified.
StackTrace Date :14/03/2023 15:07:17

--------------------------------------------------------------------------

